In [1]:
import numpy as np
import pandas as pd

#Creating a Dataframe

In [3]:
data = {
    'Name': ["Alice", "Bob", "Claire"],
    'Age': [25, 30, 27],
    'Gender': ["Female", "Male", "Female"],
    'City' : ['New York','Paris','Berlin'],
    'Salary': [50000,60000,70000]

}

df = pd.DataFrame(data)
df

     Name  Age  Gender      City  Salary
0   Alice   25  Female  New York   50000
1     Bob   30    Male     Paris   60000
2  Claire   27  Female    Berlin   70000

In [6]:
data_list = [
    ["Alice", 25, "Female", "New York", 50000],
    ["Bob", 30, "Male", "Paris", 60000],
    ["Claire", 27, "Female", "Berlin", 70000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age,','Gender','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

     Name  Age,  Gender      City  Salary
0   Alice    25  Female  New York   50000
1     Bob    30    Male     Paris   60000
2  Claire    27  Female    Berlin   70000

#Selection and indexing of columns

In [7]:
df2

     Name  Age,  Gender      City  Salary
0   Alice    25  Female  New York   50000
1     Bob    30    Male     Paris   60000
2  Claire    27  Female    Berlin   70000

In [9]:
df[0] #here indexing doesn't works the name of the columns work

KeyError: 0

In [10]:
df2['Name']

0     Alice
1       Bob
2    Claire
Name: Name, dtype: object

In [11]:
df2['City']

0    New York
1       Paris
2      Berlin
Name: City, dtype: object

In [12]:
df2[['Name','City']]

     Name      City
0   Alice  New York
1     Bob     Paris
2  Claire    Berlin

#Creating a new Column

In [13]:
df2["Designation"] = ["Manager","Developer","Analyst"]
df2

     Name  Age,  Gender      City  Salary Designation
0   Alice    25  Female  New York   50000     Manager
1     Bob    30    Male     Paris   60000   Developer
2  Claire    27  Female    Berlin   70000     Analyst

#Removing a column

In [21]:
df2.drop('Designation') #automatic axis is 0 and that is row wise so throw an error

KeyError: "['Designation'] not found in axis"

In [22]:
df2 = df2.drop('Designation',axis = 1,inplace = True) #this is vertical and this does the job
df2

KeyError: "['Designation'] not found in axis"

In [20]:
df2.columns

Index(['Name', 'Age,', 'Gender', 'City', 'Salary'], dtype='object')

In [25]:
df2.drop(['City', 'Salary'], axis=1, inplace=True)
df2

     Name  Age,  Gender
0   Alice    25  Female
1     Bob    30    Male
2  Claire    27  Female

#Selecting a row

In [37]:
data_list = [
    ["Alice", 25, "Female", "New York", 50000],
    ["Bob", 30, "Male", "Paris", 60000],
    ["Claire", 27, "Female", "Berlin", 70000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','Gender','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

     Name  Age  Gender      City  Salary
0   Alice   25  Female  New York   50000
1     Bob   30    Male     Paris   60000
2  Claire   27  Female    Berlin   70000

In [27]:
df2.loc[0] #used for selecting rows

Name         Alice
Age,            25
Gender      Female
City      New York
Salary       50000
Name: 0, dtype: object

In [29]:
df2.loc[[0,2]]

     Name  Age,  Gender      City  Salary
0   Alice    25  Female  New York   50000
2  Claire    27  Female    Berlin   70000

In [31]:
df2.iloc[2]

Name      Claire
Age,          27
Gender    Female
City      Berlin
Salary     70000
Name: 2, dtype: object

#Subset of Rows and Columns

In [32]:
df.loc[[0,1]][['City','Salary']] #for selecting both rows and columns

       City  Salary
0  New York   50000
1     Paris   60000

In [33]:
df.loc[[1,2]][['Name','Age']]

     Name  Age
1     Bob   30
2  Claire   27

#Conditional Selection

In [34]:
df2

     Name  Age,  Gender      City  Salary
0   Alice    25  Female  New York   50000
1     Bob    30    Male     Paris   60000
2  Claire    27  Female    Berlin   70000

In [38]:
#only those people whose age is greater than 25
df2[df2["Age"]>25]

     Name  Age  Gender    City  Salary
1     Bob   30    Male   Paris   60000
2  Claire   27  Female  Berlin   70000

In [41]:
#only the perople whose age is grater than 25 and their city is  berlin
df2[(df2['Age'] > 25) & (df2['City'] == 'Berlin')]

     Name  Age  Gender    City  Salary
2  Claire   27  Female  Berlin   70000