#Series in Pandas
A series is a 1-D labelled array capable of holding any data type. This axis lables are collectively called the index.
Series are vertical but vectors are horizontal

In [5]:
import numpy as np
import pandas as pd

In [10]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([1,2,3])
d = {1:10,2:20,3:30}

In [7]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(arr)

0    1
1    2
2    3
dtype: int64

In [12]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64